# Ejercicio concatenación de base de datos

In [1]:
import pandas as pd

In [2]:
#Cargar el dataset

v_2018 = './datasets/Ventas_2018.xlsx'
v_2019 = './datasets/Ventas_2019.xlsx'
v_2020 = './datasets/Ventas_2020.xlsx'
v_2021 = './datasets/Ventas_2021.xlsx'

df_1 = pd.read_excel(v_2018)
df_2 = pd.read_excel(v_2019)
df_3 = pd.read_excel(v_2020)
df_4 = pd.read_excel(v_2021)

df_ventas_previa = pd.concat([df_2,df_3,df_4], axis = 0, ignore_index = True)
df_ventas_final = pd.concat([df_1,df_ventas_previa], axis = 0, ignore_index = True)

display(df_ventas_previa)
display(df_ventas_final)

,Fecha_venta,Nit,Nombre_Cliente,Tipo Cliente,Departamento,Vendedor,Sucursal,Categoría,Producto,Linea,Cantidad,Venta,Costos
0,2019-01-03,883582190,ABASTECEMOS DE OCCIDENTE S.A,CADENA REGIONAL,CALDAS,RAUL FLOREZ RAMIREZ,NORTE,LACTEA,AREQUIPE MINI,POSTRES Y DULCES,2,17838.940000,9075.248738
1,2019-01-03,883582190,ABASTECEMOS DE OCCIDENTE S.A,CADENA REGIONAL,CALDAS,RAUL FLOREZ RAMIREZ,NORTE,LACTEA,MIGUELUCHO,POSTRES Y DULCES,5,44188.200000,24351.498020
2,2019-01-03,883582190,ABASTECEMOS DE OCCIDENTE S.A,CADENA REGIONAL,CALDAS,RAUL FLOREZ RAMIREZ,NORTE,LACTEA,MIGUELUCHO PER,POSTRES Y DULCES,3,28106.760000,15124.425801
3,2019-01-03,806153817,ALKOSTO HIPERAHORRO,CADENA NACIONAL,CALDAS,RAUL FLOREZ RAMIREZ,NORTE,LACTEA,MANTEQUILLA,ESPARCIBLES,3,28632.120000,15749.697849
4,2019-01-03,806153817,ALKOSTO HIPERAHORRO,CADENA NACIONAL,CALDAS,RAUL FLOREZ RAMIREZ,NORTE,LACTEA,MANTEQUILLA BARRA,ESPARCIBLES,2,7076.060000,4361.298856
...,...,...,...,...,...,...,...,...,...,...,...,...,...
174007,2021-12-28,820013672,TIENDA LOS RINCONES,MINIMERCADO,ANTIOQUIA,SHIRLEY MARIN MARIN,NORTE,HELADO,HELADO FRESA,HELADOS,2,6499.440000,2173.847146
174008,2021-12-28,841327549,TIENDA MARIA AUXILIADORA,MINIMERCADO,ANTIOQUIA,SHIRLEY MARIN MARIN,NORTE,HELADO,HELADO MORA,HELADOS,2,5065.503256,2302.147216
174009,2021-12-28,887188274,TIENDA OLAYA,MINIMERCADO,ANTIOQUIA,SHIRLEY MARIN MARIN,NORTE,HELADO,HELADO TRES LECHES,HELADOS,1,2659.773227,1068.661480
174010,2021-12-28,822055565,TRUJILLO JIMENEZ CAMILO ERNESTO,INSTITUCIONAL,ANTIOQUIA,SHIRLEY MARIN MARIN,NORTE,LACTEA,QUESO CREMA FIT,FIT,6,53085.180000,30451.011564
174011,2021-12-28,880572520,YADID GRANADA,MINIMERCADO,ANTIOQUIA,SHIRLEY MARIN MARIN,NORTE,LACTEA,QUESO FIT,FIT,1,4339.290000,2182.284723

,Fecha_venta,Nit,Nombre_Cliente,Tipo Cliente,Departamento,Vendedor,Sucursal,Categoría,Producto,Linea,Cantidad,Venta,Costos
0,2018-01-04,883582190,ABASTECEMOS DE OCCIDENTE S.A,CADENA REGIONAL,ANTIOQUIA,MARIA YULIETH AMARILES,NORTE,LACTEA,LECHE ENTERA,LACTEOS,3,27000.000000,11420.480226
1,2018-01-04,877794213,AGROSANAR SAS,CADENA REGIONAL,ANTIOQUIA,DIEGO MORA POSADA,SUR,LACTEA,LECHE ENTERA MINI,LACTEOS,3,25500.000000,12195.596484
2,2018-01-04,806153817,ALKOSTO HIPERAHORRO,CADENA NACIONAL,ANTIOQUIA,PAULA ANDREA ARTEAGA,CENTRO,LACTEA,LECHE DESCREMEDA,LACTEOS,2,16004.000000,8541.105250
3,2018-01-04,811548593,ALMACENES EXITO S.A,CADENA NACIONAL,ANTIOQUIA,SILVIA CAROLINA LOPEZ,NORTE,LACTEA,LECHE DESLACTOSADA,LACTEOS,2,18574.000000,14032.797920
4,2018-01-04,822018800,ALMACENES OLIMPICA,CADENA NACIONAL,ANTIOQUIA,SHIRLEY MARIN MARIN,SUR,LACTEA,LECHE SEMIDESCREMADA,LACTEOS,3,26256.000000,20842.800663
...,...,...,...,...,...,...,...,...,...,...,...,...,...
212250,2021-12-28,820013672,TIENDA LOS RINCONES,MINIMERCADO,ANTIOQUIA,SHIRLEY MARIN MARIN,NORTE,HELADO,HELADO FRESA,HELADOS,2,6499.440000,2173.847146
212251,2021-12-28,841327549,TIENDA MARIA AUXILIADORA,MINIMERCADO,ANTIOQUIA,SHIRLEY MARIN MARIN,NORTE,HELADO,HELADO MORA,HELADOS,2,5065.503256,2302.147216
212252,2021-12-28,887188274,TIENDA OLAYA,MINIMERCADO,ANTIOQUIA,SHIRLEY MARIN MARIN,NORTE,HELADO,HELADO TRES LECHES,HELADOS,1,2659.773227,1068.661480
212253,2021-12-28,822055565,TRUJILLO JIMENEZ CAMILO ERNESTO,INSTITUCIONAL,ANTIOQUIA,SHIRLEY MARIN MARIN,NORTE,LACTEA,QUESO CREMA FIT,FIT,6,53085.180000,30451.011564
212254,2021-12-28,880572520,YADID GRANADA,MINIMERCADO,ANTIOQUIA,SHIRLEY MARIN MARIN,NORTE,LACTEA,QUESO FIT,FIT,1,4339.290000,2182.284723

In [3]:
#Cargar el dataset:

#Lista de rutas de archivos

file_path = ['./datasets/Ventas_2018.xlsx','./datasets/Ventas_2019.xlsx',
              './datasets/Ventas_2020.xlsx','./datasets/Ventas_2021.xlsx']

try:
    #Crear el dataframe:
    df = pd.concat([pd.read_excel(file) for file in file_path], ignore_index=True)

    # 1.Realizar el proceso de limpieza del dataframe (No aplica):
    '''if 'Unnamed: 9' in df.columns: 
        df = df.drop(columns =['Unnamed: 9'])
        print('Se ha eliminado la columna "Unnamed: 9"')'''

    # 2. Eliminar Filas con valores nulos:
    initial_rows = df.shape[0]
    df = df.dropna()
    row_dropped = initial_rows - df.shape[0]
    print(f'Hemos Eliminado {row_dropped} filas con valores nulos')
     
    # 3. Casteamos adecuadamente el tipo de dato:
    df['Fecha_venta'] = pd.to_datetime(df['Fecha_venta'])
    print(f'Columna "Fecha_venta" transformada a formato de fecha datetime')

    # 4. Extraer las caracteristicas de la fecha
    df['Año de Venta'] = df['Fecha_venta'].dt.year
    df['Mes de Venta'] = df['Fecha_venta'].dt.month
    df['Dia de semana de venta'] = df['Fecha_venta'].dt.dayofweek #Lunes = 0 .... Domingo = 6
    print(f'Caracteristicas de fecha(Año, Mes, Día de la semana), extraidas')

    # Impresiones:
    print("Datafrae después de limpieza, primeras 5 filas:")
    print(df.head().to_markdown(index = False, numalign ='left',stralign = 'left' ))
    print('Informacion del dataframe después de la limpieza')
    print(df.info())
    print('Vaores Nulos después de la limpieza')
    print(df.isnull().sum().to_markdown(index = False, stralign ='left'))

    # Guardamos el dataset resultante:
    df.to_pickle('./datasets/Ventas_2018_2019_2020_2021_cleaned.pkl')
    print('Dataframe guardado en dataset "Ventas_2018_2019_2020_2021_cleaned.pkl"')
          
          
except Exception as e:
    print(F"Error durante la limpeza y la preparación {e}")

Hemos Eliminado 0 filas con valores nulos
Columna "Fecha_venta" transformada a formato de fecha datetime
Caracteristicas de fecha(Año, Mes, Día de la semana), extraidas
Datafrae después de limpieza, primeras 5 filas:
| Fecha_venta         | Nit       | Nombre_Cliente               | Tipo Cliente    | Departamento   | Vendedor               | Sucursal   | Categoría   | Producto             | Linea   | Cantidad   | Venta   | Costos   | Año de Venta   | Mes de Venta   | Dia de semana de venta   |
|:--------------------|:----------|:-----------------------------|:----------------|:---------------|:-----------------------|:-----------|:------------|:---------------------|:--------|:-----------|:--------|:---------|:---------------|:---------------|:-------------------------|
| 2018-01-04 00:00:00 | 883582190 | ABASTECEMOS DE OCCIDENTE S.A | CADENA REGIONAL | ANTIOQUIA      | MARIA YULIETH AMARILES | NORTE      | LACTEA      | LECHE ENTERA         | LACTEOS | 3          | 27000   | 11420.5  | 2018           | 1              | 3                        |
| 2018-01-04 00:00:00 | 877794213 | AGROSANAR SAS                | CADENA REGIONAL | ANTIOQUIA      | DIEGO MORA POSADA      | SUR        | LACTEA      | LECHE ENTERA MINI    | LACTEOS | 3          | 25500   | 12195.6  | 2018           | 1              | 3                        |
| 2018-01-04 00:00:00 | 806153817 | ALKOSTO HIPERAHORRO          | CADENA NACIONAL | ANTIOQUIA      | PAULA ANDREA ARTEAGA   | CENTRO     | LACTEA      | LECHE DESCREMEDA     | LACTEOS | 2          | 16004   | 8541.11  | 2018           | 1              | 3                        |
| 2018-01-04 00:00:00 | 811548593 | ALMACENES EXITO S.A          | CADENA NACIONAL | ANTIOQUIA      | SILVIA CAROLINA LOPEZ  | NORTE      | LACTEA      | LECHE DESLACTOSADA   | LACTEOS | 2          | 18574   | 14032.8  | 2018           | 1              | 3                        |
| 2018-01-04 00:00:00 | 822018800 | ALMACENES OLIMPICA           | CADENA NACIONAL | ANTIOQUIA      | SHIRLEY MARIN MARIN    | SUR        | LACTEA      | LECHE SEMIDESCREMADA | LACTEOS | 3          | 26256   | 20842.8  | 2018           | 1              | 3                        |
Informacion del dataframe después de la limpieza
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212255 entries, 0 to 212254
Data columns (total 16 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Fecha_venta             212255 non-null  datetime64[ns]
 1   Nit                     212255 non-null  int64
 2   Nombre_Cliente          212255 non-null  object
 3   Tipo Cliente            212255 non-null  object
 4   Departamento            212255 non-null  object
 5   Vendedor                212255 non-null  object
 6   Sucursal                212255 non-null  object
 7   Categoría               212255 non-null  object
 8   Producto                212255 non-null  object
 9   Linea                   212255 non-null  object
 10  Cantidad                212255 non-null  int64
 11  Venta                   212255 non-null  float64
 12  Costos                  212255 non-null  float64
 13  Año de Venta            212255 non-null  int32
 14  Mes de Venta            212255 non-null  int32
 15  Dia de semana de venta  212255 non-null  int32
dtypes: datetime64[ns](1), float64(2), int32(3), int64(2), object(8)
memory usage: 23.5+ MB
None
Vaores Nulos después de la limpieza
|   0 |
|----:|
|   0 |
|   0 |
|   0 |
|   0 |
|   0 |
|   0 |
|   0 |
|   0 |
|   0 |
|   0 |
|   0 |
|   0 |
|   0 |
|   0 |
|   0 |
|   0 |
Dataframe guardado en dataset "Ventas_2018_2019_2020_2021_cleaned.pkl"

# Analsis Exploratorio:
# Tarea:

Realizar el analisis exploratorio: head, info, describe
Aplicar contar nulos por columnas: df.isnull().sum()

In [4]:
print(f"5 primeras linea")
display(df.head(5))

5 primeras linea

,Fecha_venta,Nit,Nombre_Cliente,Tipo Cliente,Departamento,Vendedor,Sucursal,Categoría,Producto,Linea,Cantidad,Venta,Costos,Año de Venta,Mes de Venta,Dia de semana de venta
0,2018-01-04,883582190,ABASTECEMOS DE OCCIDENTE S.A,CADENA REGIONAL,ANTIOQUIA,MARIA YULIETH AMARILES,NORTE,LACTEA,LECHE ENTERA,LACTEOS,3,27000.0,11420.480226,2018,1,3
1,2018-01-04,877794213,AGROSANAR SAS,CADENA REGIONAL,ANTIOQUIA,DIEGO MORA POSADA,SUR,LACTEA,LECHE ENTERA MINI,LACTEOS,3,25500.0,12195.596484,2018,1,3
2,2018-01-04,806153817,ALKOSTO HIPERAHORRO,CADENA NACIONAL,ANTIOQUIA,PAULA ANDREA ARTEAGA,CENTRO,LACTEA,LECHE DESCREMEDA,LACTEOS,2,16004.0,8541.105250,2018,1,3
3,2018-01-04,811548593,ALMACENES EXITO S.A,CADENA NACIONAL,ANTIOQUIA,SILVIA CAROLINA LOPEZ,NORTE,LACTEA,LECHE DESLACTOSADA,LACTEOS,2,18574.0,14032.797920,2018,1,3
4,2018-01-04,822018800,ALMACENES OLIMPICA,CADENA NACIONAL,ANTIOQUIA,SHIRLEY MARIN MARIN,SUR,LACTEA,LECHE SEMIDESCREMADA,LACTEOS,3,26256.0,20842.800663,2018,1,3

In [5]:
print("Información concisa del DataFrame (df.info()):")
display(df.info())

Información concisa del DataFrame (df.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212255 entries, 0 to 212254
Data columns (total 16 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Fecha_venta             212255 non-null  datetime64[ns]
 1   Nit                     212255 non-null  int64
 2   Nombre_Cliente          212255 non-null  object
 3   Tipo Cliente            212255 non-null  object
 4   Departamento            212255 non-null  object
 5   Vendedor                212255 non-null  object
 6   Sucursal                212255 non-null  object
 7   Categoría               212255 non-null  object
 8   Producto                212255 non-null  object
 9   Linea                   212255 non-null  object
 10  Cantidad                212255 non-null  int64
 11  Venta                   212255 non-null  float64
 12  Costos                  212255 non-null  float64
 13  Año de Venta            212255 non-null  int32
 14  Mes de Venta            212255 non-null  int32
 15  Dia de semana de venta  212255 non-null  int32
dtypes: datetime64[ns](1), float64(2), int32(3), int64(2), object(8)
memory usage: 23.5+ MB

None

In [6]:
print("Estadísticas descriptivas para columnas numéricas (df.describe()):")
display(df.describe())

Estadísticas descriptivas para columnas numéricas (df.describe()):

,Fecha_venta,Nit,Cantidad,Venta,Costos,Año de Venta,Mes de Venta,Dia de semana de venta
count,212255,2.122550e+05,212255.000000,2.122550e+05,2.122550e+05,212255.000000,212255.000000,212255.000000
mean,2020-04-10 17:09:15.107771136,8.421852e+08,3.838586,1.883743e+04,1.153709e+04,2019.739728,6.945820,3.682542
min,2018-01-04 00:00:00,8.000712e+08,-3.000000,-2.514402e+04,-2.271596e+04,2018.000000,1.000000,0.000000
25%,2019-05-16 00:00:00,8.115486e+08,1.000000,3.643120e+03,2.170439e+03,2019.000000,4.000000,3.000000
50%,2020-06-05 00:00:00,8.376342e+08,2.000000,8.493320e+03,4.658986e+03,2020.000000,7.000000,4.000000
75%,2021-03-26 00:00:00,8.656534e+08,4.000000,1.785740e+04,1.085219e+04,2021.000000,10.000000,5.000000
max,2021-12-28 00:00:00,9.009553e+08,699.000000,6.605550e+06,2.728540e+06,2021.000000,12.000000,6.000000
std,NaN,3.064893e+07,8.074075,4.791688e+04,2.914838e+04,1.081845,3.345325,1.904372

In [7]:
# Productos con Precio_Unitario ausente (NaN)
precio_ausente = df[df['Venta'].isnull()]
print("Productos con Venta ausente:")

Productos con Venta ausente:

**Paso 3: Ingenieria de Modelo:**

In [8]:
from sklearn.preprocessing import OneHotEncoder #Asignar valores categorias
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
import joblib
import scipy.sparse

# linklibrerias para el entrenamiento de la ml:
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [9]:
file_path = './datasets/Ventas_2018_2019_2020_2021_cleaned.pkl'

try:
    pd.read_pickle(file_path)
    print(f'Cargado el dataframe desde {file_path}, exitosamente')

    #1. Empezamos con la ingenieria de caracteristicas:

    df['Margen Ganancia'] = df['Venta'] - df['Costos']
    print(f"Caracteristica \'Margen de Ganancia\' creada")

    #2. Ingenieria de caracteristicas: ingreso total de venta

    df['Ingreso Total Venta'] =df['Venta'] * df['Cantidad']
    print(f"Caracteristica \'Ingreso Total Venta\' creada")

    #3. Ingenieria de caracteristicas: Ganancia total de venta

    df['Ganancia Total Venta'] =df['Margen Ganancia'] * df['Cantidad']
    print(f"Caracteristica \'Ingreso Total Venta\' creada")

    #4. Seleccion de la variable objetivo:

    target_variable = 'Ingreso Total Venta'

    # Excluimos las columnas que no se usan y las que usamos para calcular el target_variable e incluimos esta mism para evitar el data leake
 
    # Caracteristicas a descartar:

    features_to_exclude = ['Fecha_venta','Nombre_Cliente',target_variable,'Venta','Cantidad']
    
    features = [col for col in df.columns if col not in features_to_exclude]
    print(f'Caracteristicas para ingenieria: {features}')

    # Identificar caracteristicas categoricas y numericas:

    categorical_features = df[features].select_dtypes(include = ['object']).columns
    numerical_features = df[features].select_dtypes(include = ['int64','float64','int32']).columns

    #Imprimamos el resultado:
    print(f"Varibale Objetivo: {target_variable}")
    print(f"Caracteristicas Categoricas: {list()}")
    print(f"Caracteristicas Numericas: {list(numerical_features)}")

    #5. Codificar variables categoricas (One-Hot-Encoding) y pasar numericas:
    preprocessor = ColumnTransformer(
        transformers = [
            ("num", "passthrough", numerical_features),
            ("cat", OneHotEncoder(handle_unknown = "ignore"), categorical_features)
        ]
    )
    #Aplicar Transformaciones:

    x = df[features]
    y = df[target_variable]

    x_processed = preprocessor.fit_transform(x)

    # Convertir en un arreglo denso si es una matriz dispersa:

    if scipy.sparse.issparse(x_processed):
        x_processed = x_processed.toarray()

    # Obtenemos los nombres de las nuevas colummnas despues del preprocesamiento:
    all_features_names = preprocessor.get_feature_names_out()

    x_processed_dataframe = pd.DataFrame(x_processed,columns = all_features_names, index = df.index)

    print(f"Dataframe después de la ingenieria de caracteristicas y codificacion:")
    display(x_processed_dataframe.head())
    print(f"Dimensions del dataset después de todo esto: ")
    print(x_processed_dataframe.shape)

    # Guardar el modelo generado

    joblib.dump(preprocessor,"./Modelo/model.pkl")

    # Guardar el modelo generado
    x_processed_dataframe.to_pickle("./datasets/x_processed_dataframe_df.pkl")
    y.to_pickle('./datasets/y_target.pkl')

except Exception as e:
    print(f'error presentado al guardar el modelo {e}')

Cargado el dataframe desde ./datasets/Ventas_2018_2019_2020_2021_cleaned.pkl, exitosamente
Caracteristica 'Margen de Ganancia' creada
Caracteristica 'Ingreso Total Venta' creada
Caracteristica 'Ingreso Total Venta' creada
Caracteristicas para ingenieria: ['Nit', 'Tipo Cliente', 'Departamento', 'Vendedor', 'Sucursal', 'Categoría', 'Producto', 'Linea', 'Costos', 'Año de Venta', 'Mes de Venta', 'Dia de semana de venta', 'Margen Ganancia', 'Ganancia Total Venta']
Varibale Objetivo: Ingreso Total Venta
Caracteristicas Categoricas: []
Caracteristicas Numericas: ['Nit', 'Costos', 'Año de Venta', 'Mes de Venta', 'Dia de semana de venta', 'Margen Ganancia', 'Ganancia Total Venta']
Dataframe después de la ingenieria de caracteristicas y codificacion:

,num__Nit,num__Costos,num__Año de Venta,num__Mes de Venta,num__Dia de semana de venta,num__Margen Ganancia,num__Ganancia Total Venta,cat__Tipo Cliente_CADENA NACIONAL,cat__Tipo Cliente_CADENA REGIONAL,cat__Tipo Cliente_DISTRIBUIDOR,...,cat__Producto_YOGURT TARRO MINI,cat__Linea_CARNES FRIAS,cat__Linea_ESPARCIBLES,cat__Linea_FIT,cat__Linea_HELADOS,cat__Linea_JUGOS Y REFRESCOS,cat__Linea_KIDS,cat__Linea_LACTEOS,cat__Linea_POSTRES Y DULCES,cat__Linea_QUESOS
0,883582190.0,11420.480226,2018.0,1.0,3.0,15579.519774,46738.559322,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,877794213.0,12195.596484,2018.0,1.0,3.0,13304.403516,39913.210548,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,806153817.0,8541.105250,2018.0,1.0,3.0,7462.894750,14925.789500,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,811548593.0,14032.797920,2018.0,1.0,3.0,4541.202080,9082.404160,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,822018800.0,20842.800663,2018.0,1.0,3.0,5413.199337,16239.598011,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

Dimensions del dataset después de todo esto:
(212255, 123)

# Paso 4: Entrenamiento y evaluación de modelo

In [10]:
# Cargar los dataframes procesados:

x_processed_dataframe = pd.read_pickle('./datasets/x_processed_dataframe_df.pkl')
y_target = pd.read_pickle('./datasets/y_target.pkl')
x_processed_dataframe

# Division para entrenamiento y evaluación

x_train,x_test,y_train,y_test = train_test_split(x_processed_dataframe, y_target, test_size = 0.2, random_state = 42 )

print(f"Dimensiones del conjunto de pruebas: x_test = {x_train.shape}, y_test: {y_test.shape}")
print(f"Dimensiones del conjunto de entrenamiento: x_test = {x_train.shape}. y_test: {y_train.shape}")

Dimensiones del conjunto de pruebas: x_test = (169804, 123), y_test: (42451,)
Dimensiones del conjunto de entrenamiento: x_test = (169804, 123). y_test: (169804,)

# Iniciamos el entrenamiento

In [11]:
print(f"Iniciando el entrenamiento")
model = RandomForestRegressor(n_estimators=100, random_state = 42, n_jobs = -1)
model.fit(x_train,y_train)
print(f"Entrenamiento concluido con éxito")

Iniciando el entrenamiento
Entrenamiento concluido con éxito

# Evaluando el modelo

In [12]:
# Predicciones:

y_pred = model.predict(x_test)

#Evaluación de lo predicho:

mse = mean_squared_error(y_test,y_pred)
r2 = r2_score(y_test, y_pred)

# Imprimir los resultados:

In [13]:
print(f'\nResultados de la evaluación del modelo')
print(f'El error cuadratico medio (MSE): {mse: .2F}')
print(f'Coeficiente de determinanción (R2): {r2: .2f}')

Resultados de la evaluación del modelo
El error cuadratico medio (MSE):  40083055178624.93
Coeficiente de determinanción (R2):  0.89

# Guardamos el modelo

In [14]:
joblib.dump(model,'./Modelo/modelo_train.pkl ')
print('Hemos guardado el modelo entrenado')

Hemos guardado el modelo entrenado

# Optimización del modelo

In [15]:
x_processed_dataframe = pd.read_pickle('./datasets/x_processed_dataframe_df.pkl')
y_target = pd.read_pickle('./datasets/y_target.pkl')

print("Dataframes cargados")

# Division para entrenamiento y evaluación

x_train,x_test,y_train,y_test = train_test_split(x_processed_dataframe, y_target, test_size = 0.2, random_state = 42 )

print(f"Dimensiones del conjunto de pruebas: x_test = {x_train.shape}, y_test: {y_test.shape}")
print(f"Dimensiones del conjunto de entrenamiento: x_test = {x_train.shape}. y_test: {y_train.shape}")

Dataframes cargados
Dimensiones del conjunto de pruebas: x_test = (169804, 123), y_test: (42451,)
Dimensiones del conjunto de entrenamiento: x_test = (169804, 123). y_test: (169804,)

In [16]:
model = RandomForestRegressor(random_state = 42, n_jobs = -1)

param_grid = {
"n_estimators" : [50,100,150], #Arboles
    "max_depth": [10,20,None] #Profundidad del bosque
}

In [ ]:
print("Iniciando busquedad de hiperparametros con GridSearchCV")
Grid_search = GridSearchCV(estimator = model, param_grid = param_grid, cv = 3, n_jobs=-1,verbose=2,
scoring="neg_mean_squared_error"
)

Grid_search.fit(x_train,y_train)

print("Busqueda de hiperparametros completada")

Iniciando busquedad de hiperparametros con GridSearchCV
Fitting 3 folds for each of 9 candidates, totalling 27 fits

In [ ]:
best_params = Grid_search.best_params_
best_model = Grid_search.best_estimator_

print(f"\nMejores Hiperparametos encontrados: {best_params}")

## .....Evaluación y creación de mejor modelo.....

In [ ]:
y_pred_optimized = best_model.predict(x_test)

mse_optimized = mean_squared_error(y_test,y_pred_optimized)
r2_optimized = r2_score(y_test,y_pred_optimized)

#impresiones:

print(f'\nResultados de la evaluación del modelo')
print(f'El error cuadratico medio (MSE): {mse_optimized: .2F}')
print(f'Coeficiente de determinanción (R2): {r2_optimized: .2f}')

# ----Guardamos el modelo----

In [ ]:
joblib.dump(best_model,'./Modelo/best_model.pkl ')
print('Hemos guardado el modelo entrenado')

# --------Realizar Predicciones-------

In [ ]:
# Importamos 1. Modelo de preprocesamiento:
PREPROCESSOR_PATH ="./Modelo/model.pkl"
MODEL_PATH = './Modelo/best_model.pkl'
ORIGINAL_DF_PATH = './datasets/BD_Ventas_Tech_cleaned.pkl'

# Cargarlos:
try:
    PREPROCESSOR = joblib.load(PREPROCESSOR_PATH)
    print('Ha sido un éxito la carga del preprocesador')

    MODEL = joblib.load(MODEL_PATH)

    ORIGINAL_DF = pd.read_pickle(ORIGINAL_DF_PATH)
    
except Exception as e:
    print('No se pudo cargar desde la ruta indicada',e)


target_variable ="Ingreso Total Venta"

# Caracteristicas a descartar:

features_to_exclude = ['Fecha de Venta','Nombre Cliente',target_variable,'Precio Unidad','Cantidad Vendida']
FEATURES_FOR_PREPROCESSOR = [col for col in df.columns if col not in features_to_exclude]

# Adicionamos las columnas que harán falta:

#FEATURES_FOR_PREPROCESSOR.extend(['Margen Ganancia','Ganancia Total Venta'])
print(f'Caracteristicas para ingenieria: {FEATURES_FOR_PREPROCESSOR}')

In [ ]:
def prediccion_total_ingreso(input_data: dict):
    df_input = pd.DataFrame([input_data])
    display(df_input)
    try:
        df_input['Fecha_venta'] = pd.to_datetime(df_input['Fecha_venta'])
        df_input['Año de Venta'] = df_input['Fecha_venta'].dt.year 
        df_input['Mes de Venta'] = df_input['Fecha_venta'].dt.month
        df_input['Dia de semana de venta'] = df_input['Fecha_venta'].dt.day_of_week
        df_input['Margen Ganancia'] = df['Venta'] * df_input['Costos']
        df_input['Ganancia Total Venta'] = df_input['Margen Ganancia'] * df_input['Cantidad']
    
        df_input_processed = df_input[FEATURES_FOR_PREPROCESSOR]
        display(df_input_processed)
        x_input_processed = PREPROCESSOR.transform(df_input_processed)
    
        prediccion = MODEL.predict(x_input_processed)[0]
    
        return prediccion
        
    
    except Exception as e:
        print(f'Error al crear el dataframe de ingreso {e}')

In [ ]:
data_test = {"Fecha_venta":"2023-01-08",
             "Departamento": "CHOCO, SUR", 
             "Producto":"LIMONADA NATURAL",
             "Linea":"JUGOS Y REFRESCOS",
             "Categoría":"BEBIDAS",
             "Venta":2.300,
             "Costos": 1.077,
    "Cantidad": 1.0}
    
data_test

In [ ]:
predicho = prediccion_total_ingreso(data_test)
print(f'El ingreso total de venta esperado es: {predicho}')